### ISSUE TITLE
Problems with translation of single words

### ISSUE THREAD

**Issue by proycon** [proycon/oersetter-webservice#1]
From mail by Hindrik:
> Losse woorden worden blijkbaar niet meer vertaald door Oersetter. Ik heb het bekeken en inderdaad komen thuis en wedstrijd er niet in het Fries 
> uit. Dit gebeurt bij het vertalen van een woord. In zinnetjes of bij meerdere woorden tegelijk lijkt het goed te gaan:                                                                         
> Cambuur won de wedstrijd = Cambuur wûn de wedstriid is correct vertaald.                                                                                                                       
> Wedstrijd wedstrijd, wedstrijd. Wedstrijden = Wedstriid wedstryd , wedstriid . Wedstriden . is correct vertaald.

**Comment by proycon** [comment]
(postponing investigation until at least february)

**Comment by proycon** [comment]
@eduarddrenth  Sorry that this was delayed so much. I just implemented a quick patch (not very elegant but it should get the job done). I'll deploy it later today.

**Comment by eduarddrenth** [comment]
Did you get a chance to deploy it? I don't see any change yet

**Comment by proycon** [comment]
The LaMachine update got stalled as I need the system administrators to install two packages first.

**Comment by eduarddrenth** [comment]
one question: do you remove the dot after translating? Otherwise the result may be unexpected to users.

**Comment by proycon** [comment]
Good point, at the moment it doesn't yet removed yet no.

**Comment by proycon** [comment]
It's deployed now but something seems wrong still for single words. I did also implement automatic restarts of the background servers now so hopefully that helps.

**Comment by eduarddrenth** [comment]
That's a pitty, I looked at the python code, do not quite understand it, never programmed python...

But what I see:

- an unused variable singleword
- read all lines in a file
- when condition firstline evaluates to true (non empty?) quit the function (return False)

so the . is actually never added?

But again, I'm not a python man

**Comment by proycon** [comment]
I disabled the patch and added something new, bit on a hunch, I'll deploy and test it late tonight when traffic is low  (no separate local development environment unfortunately because the moses servers take so much memory)

**Comment by proycon** [comment]
The new fix solves it finally, it is being deployed right now (takes a while)
